server.port=8085
server.servlet.contextPath=/PharmacyRest

spring.datasource.url=jdbc:postgresql://primal-flyer-13649.8nj.gcp-europe-west1.cockroachlabs.cloud:26257/postgres
spring.datasource.username=zaricu22_gmail_com
spring.datasource.password=uH8kRDjA37zccIU6Ogve2w
spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
# spring.jpa.database-platform=org.hibernate.dialect.CockroachDB201Dialect

application.security.jwt.secrete-key=D3saLo5vgxWtBEZ/J1/QIgIsFgCuRx0EMm9/zTxcTX4=
# a day (86400000 s)
application.security.jwt.access-token-expiration=86400000 
# seven days (604800000 s)
application.security.jwt.refresh-token-expiration=604800000 

